[package]
name = "auth-service"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
axum = "0.8"
tokio-postgres="0.7"
jsonwebtoken = "8.2"
base64 = "0.22.1"